"""Initial migration

Revision ID: ae40a8cf38b0
Revises: 
Create Date: 2025-07-18 15:19:48.361336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae40a8cf38b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_number', sa.String(length=80), nullable=False),
    sa.Column('firstname', sa.String(length=120), nullable=False),
    sa.Column('middlename', sa.String(length=120), nullable=True),
    sa.Column('department', sa.String(length=120), nullable=True),
    sa.Column('programme', sa.String(length=120), nullable=True),
    sa.Column('academic_year', sa.String(length=20), nullable=True),
    sa.Column('year_of_study', sa.String(length=20), nullable=True),
    sa.Column('semester', sa.String(length=20), nullable=True),
    sa.Column('registration_status', sa.Integer(), nullable=True),
    sa.Column('passport_size_path', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number')
    )
    op.create_table('attendance_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('record_type', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance_record')
    op.drop_table('student')
    # ### end Alembic commands ###
